# Week 5 Assignment: Utilizing Pandas and PandasAI for Data Filtering

***

**Import libraries**

In [17]:
import pandas as pd
import numpy as np

from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

***
# Data Loading

* Load a CSV file containing at least 500 records and four columns into a regular Pandas data frame and a PandasAI data frame.

In [18]:
np.random.seed(42) # for reproducibility

n = 750 # number of samples

# Generate synthetic data

categories = ["Electronics", "Clothing", "Groceries", "Home", "Beauty"]
regions = ["North", "South", "East", "West"]
payment_methods = ["Credit Card", "Debit Card", "Cash", "Mobile Pay"]

df_synthetic = pd.DataFrame({
    "CustomerID": np.random.randint(1000, 9999, n),
    "TransactionID": np.arange(1, n + 1),
    "Category": np.random.choice(categories, n),
    "Region": np.random.choice(regions, n),
    "PaymentMethod": np.random.choice(payment_methods, n),
    "Amount": np.round(np.random.uniform(5, 500, n), 2)
    })

# Save to CSV
output_path = "synthetic_transactions.csv"
df_synthetic.to_csv(output_path, index=False)
print(f"Synthetic dataset saved to {output_path}")

Synthetic dataset saved to synthetic_transactions.csv

In [19]:
df_synthetic.head() # Display the first few rows of the synthetic dataset

   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        1860              2  Electronics   East    Mobile Pay  244.07
2        6390              3     Clothing   West          Cash   71.07
3        6191              4         Home  North    Mobile Pay   44.90
4        6734              5  Electronics  North   Credit Card  365.33

***
# Load CSV into Pandas

In [20]:
df = pd.read_csv("synthetic_transactions.csv")
print(df.shape) # Check the shape of the dataset
print(df.head()) # Display the first few rows of the dataset

(750, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        1860              2  Electronics   East    Mobile Pay  244.07
2        6390              3     Clothing   West          Cash   71.07
3        6191              4         Home  North    Mobile Pay   44.90
4        6734              5  Electronics  North   Credit Card  365.33

# Load CSV into PandasAI

In [21]:
# Import necessary libraries for PandasAI
import pandasai as pai
from pandasai_litellm import LiteLLM
from openai import OpenAI

client = OpenAI( api_key=api_key) # Initialize the OpenAI client with the API key

In [22]:
llm = LiteLLM(
    model="gpt-5-nano", # Specify the model to use
    api_key=api_key
) # Initialize the LiteLLM with the specified model and API key

pai.config.set({
    "llm": llm
}) # Set the LLM for PandasAI

In [23]:
df_ai = pai.read_csv("synthetic_transactions.csv") # Load the dataset using PandasAI
print(df_ai.shape) # Check the shape of the dataset loaded with PandasAI
print(df_ai.head()) # Display the first few rows of the dataset loaded with PandasAI

(750, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        1860              2  Electronics   East    Mobile Pay  244.07
2        6390              3     Clothing   West          Cash   71.07
3        6191              4         Home  North    Mobile Pay   44.90
4        6734              5  Electronics  North   Credit Card  365.33

***
# Data Filtering Tasks

➡︎ Single Column Criteria: Use regular Pandas and PandasAI to filter the data frame based on a specified criterion in one column.
   * Regular Pandas: Use conditions to filter the dataframe based on a criterion in one column. For example, df[df['column_name'] == 'value'].

   * PandasAI: Apply a similar filtering method using PandasAI’s syntax, which might differ slightly depending on its API.

**Single column Dataset w/ Pandas**

In [24]:
# Filter Dataset w/ Pandas
pandas_single = df[df["Category"] == "Electronics"]
print(pandas_single.shape) # Check the shape of the filtered dataset
print(pandas_single.head()) # Display the first few rows of the filtered dataset

(154, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        1860              2  Electronics   East    Mobile Pay  244.07
4        6734              5  Electronics  North   Credit Card  365.33
5        7265              6  Electronics   West    Mobile Pay  250.75
8        6578              9  Electronics   East    Debit Card  383.93

**Single column Dataset w/ PandasAI**

In [25]:
type(ai_single) # Check the type of the filtered dataset from PandasAI

pandasai.core.response.dataframe.DataFrameResponse

In [26]:
print(ai_single) # Display the filtered dataset from PandasAI

     CustomerID  TransactionID     Category Region PaymentMethod  Amount
0          8270              1  Electronics  North   Credit Card  231.80
1          1860              2  Electronics   East    Mobile Pay  244.07
2          6734              5  Electronics  North   Credit Card  365.33
3          7265              6  Electronics   West    Mobile Pay  250.75
4          6578              9  Electronics   East    Debit Card  383.93
..          ...            ...          ...    ...           ...     ...
149        2276            721  Electronics   West   Credit Card   67.15
150        1638            724  Electronics   West          Cash  404.54
151        2646            734  Electronics  North          Cash  153.40
152        7949            743  Electronics  North          Cash  202.01
153        9152            747  Electronics  North   Credit Card  127.07

[154 rows x 6 columns]

In [27]:
# Filter Dataset w/ PandasAI
ai_single = df_ai.chat(
    "Return a dataframe containing only rows where Category is Electronics"
)

ai_single_df = ai_single.value
print(ai_single_df.shape)
print(ai_single_df.head())

(154, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        1860              2  Electronics   East    Mobile Pay  244.07
2        6734              5  Electronics  North   Credit Card  365.33
3        7265              6  Electronics   West    Mobile Pay  250.75
4        6578              9  Electronics   East    Debit Card  383.93

***
➡︎  Two Columns Criteria: Present the code used to filter the data frame based on criteria in two columns using both regular Pandas and PandasAI.
* Regular Pandas: Combine conditions for two columns, such as df[(df['column1'] == 'value1') & (df['column2'] == 'value2')].

* PandasAI: Perform the same operation, adjusting for any differences in handling logical operations.

**Two columns w/ Pandas**

In [28]:
pandas_two = df[
    (df["Category"] == "Electronics") &
    (df["Region"] == "North")
]
pandas_two.head()

    CustomerID  TransactionID     Category Region PaymentMethod  Amount
0         8270              1  Electronics  North   Credit Card  231.80
4         6734              5  Electronics  North   Credit Card  365.33
17        2184             18  Electronics  North    Debit Card  144.68
30        2899             31  Electronics  North    Mobile Pay  453.69
62        2016             63  Electronics  North   Credit Card  430.77

**Two columns Dataset w/ PandasAI**

In [29]:
ai_two = df_ai.chat(
    "Return a dataframe containing only rows where Category is Electronics and Region is North"
)

ai_two_df = ai_two.value
print(ai_two_df.shape)
print(ai_two_df.head())

(36, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        6734              5  Electronics  North   Credit Card  365.33
2        2184             18  Electronics  North    Debit Card  144.68
3        2899             31  Electronics  North    Mobile Pay  453.69
4        2016             63  Electronics  North   Credit Card  430.77

***
➡︎  Three Columns Criteria: Demonstrate how to filter the data frame using criteria from three columns using both regular Pandas and PandasAI.

 * Regular Pandas: Extend the conditions to three columns, ensuring logical operations are correctly applied, like df[(df['column1'] == 'value1') & (df['column2'] == 'value2') & (df['column3'] == 'value3')].

 * PandasAI: Again, apply these filters, considering any specific nuances of the PandasAI library.

**Three columns Dataset w/ Pandas**

In [31]:
pandas_three = df[
    (df["Category"] == "Electronics") &
    (df["Region"] == "North") &
    (df["PaymentMethod"] == "Credit Card")
]
pandas_three.head()

     CustomerID  TransactionID     Category Region PaymentMethod  Amount
0          8270              1  Electronics  North   Credit Card  231.80
4          6734              5  Electronics  North   Credit Card  365.33
62         2016             63  Electronics  North   Credit Card  430.77
365        3838            366  Electronics  North   Credit Card  184.15
374        1559            375  Electronics  North   Credit Card  451.71

**Three columns Dataset w/ PandasAI**

In [ ]:
ai_three = df_ai.chat(
    "Return a dataframe containing only rows where Category is Electronics, Region is North, and Payment_Method is Credit Card"
)

ai_three_df = ai_three.value
print(ai_three_df.shape)
print(ai_three_df.head())

(6, 6)
   CustomerID  TransactionID     Category Region PaymentMethod  Amount
0        8270              1  Electronics  North   Credit Card  231.80
1        6734              5  Electronics  North   Credit Card  365.33
2        2016             63  Electronics  North   Credit Card  430.77
3        3838            366  Electronics  North   Credit Card  184.15
4        1559            375  Electronics  North   Credit Card  451.71

***

# Comparison

Pandas

In [32]:
print("Single-column filter rows (Pandas):", len(pandas_single))
print("Two-column filter rows (Pandas):", len(pandas_two))
print("Three-column filter rows (Pandas):", len(pandas_three))

Single-column filter rows (Pandas): 154
Two-column filter rows (Pandas): 36
Three-column filter rows (Pandas): 6

PandasAI

In [33]:
print("Regular Pandas is precise and reproducible.")
print("PandasAI is easier for natural language queries, but results depend on prompt wording and LLM behavior.")

Regular Pandas is precise and reproducible.
PandasAI is easier for natural language queries, but results depend on prompt wording and LLM behavior.